import Layout from './components/Layout/Layout.jsx'
import Sidebar from './components/Sidebar/Sidebar.jsx'
import Canvas from './components/Canvas/Canvas.jsx'
import { PaletteProvider } from './state/PaletteContext'

const DEFAULT_SECTIONS = [
  {
      title: 'Diagrams',
      key: 'diagrams',
      items: [
        { type: 'init-diag', label: 'New Diagram', opened: true, nodes: [], edges: [] }
      ]
  },
  {
    title: 'Wires',
    key: 'wires',
    items: [],
  },
  {
    title: 'Boxes',
    key: 'boxes',
    items: [],
  },
  {
    title: 'Equations',
    key: 'equations',
    items: []
  }
];

export default function App() {
  return (
    <>
      <PaletteProvider initialSections={DEFAULT_SECTIONS}>
        <Layout sidebar={<Sidebar />}>
          <Canvas />
        </Layout>
      </PaletteProvider>
      {/* Floating helper text at the bottom center of the canvas. */}
      <div
          style={{
              position: 'absolute',
              left: '50%',
              transform: 'translateX(-50%)',
              bottom: "2px",
              pointerEvents: 'none',
              fontSize: "0.6rem",
          }}
      >
          This app was almost entirely generated by gpt-5-mini. Don't use it for anything serious!
      </div>
    </>
  )
}
